# هذا هو ملف تكوين أساسي لمساعدتك على بدء استخدام GitHub Actions
name: CI

# يتحكم في وقت تشغيل الإجراءات
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# يسمح بتشغيل هذا الإجراء يدويًا من علامة تبويب الإجراءات
workflow_dispatch:

# يتكون تشغيل الإجراء من وظيفة واحدة أو أكثر يمكن أن تعمل بالتسلسل أو بالتوازي
jobs:
  build:
    # نوع الخادم الذي سيتم تشغيل الوظيفة عليه
    runs-on: ubuntu-latest

    # الخطوات التي تمثل تسلسل المهام التي سيتم تنفيذها كجزء من الوظيفة
    steps:
      # التحقق من مستودعك بحيث يمكن للوظيفة الوصول إليه
      - uses: actions/checkout@v4

      # تنفيذ أمر واحد باستخدام shell
      - name: Run a one-line script
        run: echo Hello, world!

      # تنفيذ مجموعة من الأوامر باستخدام shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
